version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    restart: always
    ports:
      - 90:90
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
  portainer:
    image: portainer/portainer:1.20.2
    restart: always
    ports:
      - "32768"
    networks:
      - web
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data portainer/portainer
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.portainer.frontend.rule=Host:portainer.localhost"
      - "traefik.portainer.port=9000"
      - "traefik.portainer.protocol=http"
  jenkins:
    image: jenkins/jenkins:2.180-slim
    restart: always
    ports:
      - "9090"
    networks:
      - web
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.jenkins.frontend.rule=Host:jenkins.localhost"
      - "traefik.jenkins.port=9090"
      - "traefik.jenkins.protocol=http"

networks:
  web:
    external: 
      name: web
